### ISSUE TITLE
Upgrade the build system

### ISSUE THREAD

**Issue by shadxx7** [ossdaiict/sbg-daiict-website#1]
Upgrading the build system currently requires you to rewrite the webpack and babel config with the corresponding latest plugins and presets. An alternative to this would be to use [create-react-app](https://github.com/facebook/create-react-app) and use [rescripts](https://github.com/harrysolovay/rescripts) to update the webpack/babel config to match the older configuration.

**Comment by rannie-peralta** [comment]
Can I work on this?

**Comment by shadxx7** [comment]
Yea sure! If you need any help comment here 😄

**Comment by rannie-peralta** [comment]
Unfortunately, my internet connection is not as good to clone this repo :disappointed:

**Comment by harshzalavadiya** [comment]
I would love to work on this,
Will submit PR as soon as it's migrated to CRA

**Comment by shadxx7** [comment]
Great!

**Comment by harshzalavadiya** [comment]
hi @shadxx7 
Just checking in for the PR
