### ISSUE TITLE
Clicking on another tab in the committee wise member panel causes a crash

### ISSUE THREAD

**Issue by shadxx7** [ossdaiict/sbg-daiict-website#15]
![tab-bug](https://user-images.githubusercontent.com/22408263/67015095-9f40af80-f113-11e9-9146-06e392f33821.gif)

Investigate the bug and find a possible solution.

**Comment by nik72619c** [comment]
I'll try it out

**Comment by shadxx7** [comment]
Great!

**Comment by nik72619c** [comment]
I guess there's some other issue as well - on hovering on any chart, the data disappears

**Comment by shadxx7** [comment]
Yup, that has been reported in #16

**Comment by nik72619c** [comment]
Could you please guide me with this error , any direction to think ?
I know exactly where the error is but I cant really find a way to resolve it. It looks like recharts is internally crashing but i dont know why

**Comment by nik72619c** [comment]
> Hey, so from what I understand the crash is being caused by some internal conflict of how recharts renders its chart and how react-bootstrap is rendering the tabs. Since mostly these are caused by internal library conflicts I recommend you remove the tabs and move the 2 different donuts(piecharts) to 2 different panels for now.

Yes, I feel the same. I'd add them into different panels then. Thanks for the help :)

**Comment by osmarpetry** [comment]
Just outdated package, the PR is there: https://github.com/ossdaiict/sbg-daiict-website/pull/19
