### ISSUE TITLE
Committe wise member Donut not working properly 

### ISSUE THREAD

**Issue by shadxx7** [ossdaiict/sbg-daiict-website#16]
**Describe the bug**
The committee wise member count donut component does not work as intended. Nothing is displayed on hover.

**To Reproduce**
1. Go to the home page
2. Scroll down until you come across the "Committee wise Members' Count" Panel and then hover on the pie chart.

**Expected behavior**
Information about the committee and amount of members is to be displayed.

**Additional context**
This is mostly happening because of the use of deprecated API of [recharts](http://recharts.org/en-US/). Perhaps updating the Donut.js/LabeledPie.js component according to the new API of recharts would help.

**Comment by osmarpetry** [comment]
I'll try it. Anyone can feel free to try to solve this issue too

**Comment by osmarpetry** [comment]
Just outdated package, the PR is there: https://github.com/ossdaiict/sbg-daiict-website/pull/19

**Comment by osmarpetry** [comment]
Ops, I referenced the wrong issue

**Comment by shadxx7** [comment]
This issue is still up for grabs :)

**Comment by hitgo00** [comment]
I'm trying it.

**Comment by shadxx7** [comment]
#25 solves this.
