### ISSUE TITLE
Moving to reactstrap and bootstrap 4

### ISSUE THREAD

**Issue by statebait** [ossdaiict/sbg-daiict-website#24]
Solving this issue will require you to rewrite all components using the [reactstrap](https://reactstrap.github.io/) library. As all components are currently written with an older version of react-bootstrap which uses bootstrap 3, appropriate changes need to be made which will accommodate all the changes made in bootstrap from 3 to 4.

**Comment by marcelorl** [comment]
i'm taking this one

**Comment by shadxx7** [comment]
Great!

**Comment by akankshajai** [comment]
Is this still open? I would like to work on it.

**Comment by shadxx7** [comment]
Hey @akankshajai , currently @marcelorl is working on this issue, in the meanwhile you can check out issue #28

**Comment by akankshajai** [comment]
Sure , I will work on #28

**Comment by shadxx7** [comment]
Hey @akankshajai , we just received a PR on #28, I am really sorry 😞 but we will be adding more issues soon so do stay tuned

**Comment by shadxx7** [comment]
@marcelorl are you still working on this?

**Comment by marcelorl** [comment]
@shadxx7 yes, I am.

I have mapped all the places where I will have to change and I will be working on then today.

**Comment by shadxx7** [comment]
Great!

**Comment by shadxx7** [comment]
Hey @marcelorl , any progress?

**Comment by statebait** [comment]
Hey @marcelorl , are you still working on this?

**Comment by statebait** [comment]
This issue is up for grabs again!
