### ISSUE TITLE
Pie charts glitching out

### ISSUE THREAD

**Issue by shadxx7** [ossdaiict/sbg-daiict-website#28]
**Describe the bug**
Labelled Pie component glitches out on hover

**To Reproduce**
1. Go to the home page
2. Scroll down to the 'Activity Statistics' Panel
3. Hover on the Pie charts

**Expected behavior**
Should show values instead of glitching out

**Additional context**
This is mostly happening because of the use of deprecated API of recharts. Perhaps updating the LabeledPie.js component according to the new API of recharts would help.

**Comment by hitgo00** [comment]
Working on this issue!

**Comment by shadxx7** [comment]
fixed in #29
