### ISSUE TITLE
Update Contributors in README

### ISSUE THREAD

**Issue by statebait** [ossdaiict/sbg-daiict-website#5]

**Comment by shadxx7** [comment]
@all-contributors please add @shadxx7 for infrastructure and code

**Comment by shadxx7** [comment]
@all-contributors please add @aaditya-thakkar for bug, code and maintenance

**Comment by shadxx7** [comment]
@all-contributors please add @aaditya-thakkar for code and design

**Comment by shadxx7** [comment]
@all-contributors please add @yash2407 for content

**Comment by shadxx7** [comment]
@all-contributors please add @yash2407 for content

**Comment by shadxx7** [comment]
@all-contributors please add @osmarpetry for code

**Comment by shadxx7** [comment]
@all-contributors please add @osmarpetry for code

**Comment by statebait** [comment]
@all-contributors please add @sanket143 for content and code

**Comment by statebait** [comment]
@all-contributors please add @Vishu26 for content and code
